---
dependency:
  name: galaxy
  options: 
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ./molecule/default/yaml-lint.yml
#    config-file: ./yaml-lint.yml yaml-lint.yml
platforms:
  - name: instance
    image: ubuntu
    groups: 
      - example
    children:
      - example_1
provisioner:
  name: ansible
  options:
    vvv: True
#      group_vars: ../../../group_vars/
  playbooks:
#    create: ./molecule/default/create.yml
    create: ./create.yml
#    destroy: ./molecule/default/destroy.yml 
    destroy: ./destroy.yml 
#   links:
  inventory:
    host_vars:
      instance:
        host_group_vars_host_molecule_yml: True
        host_group_vars_host_vars_dir: True 
    group_vars:
      example:
        host_group_vars_example_group_one_molecule_yml: True
        host_group_vars_example_group_two_molecule_yml: True
        host_group_vars_group_vars_dir: True
      example_1:
        host_group_vars_example_1_child_group_molecule_yml: True
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
